param(
  [Parameter(Mandatory = $false)]
  [string]$EnvFile = ".env",
  [Parameter(Mandatory = $false)]
  [string]$OutputRoot = "dist/lan-bundles",
  [Parameter(Mandatory = $false)]
  [string]$ServerIp = "192.168.1.187",
  [Parameter(Mandatory = $false)]
  [int]$ServerPort = 3000,
  [Parameter(Mandatory = $false)]
  [string]$ClientHostName = "DESKTOP-HT0U9M8",
  [Parameter(Mandatory = $false)]
  [string]$ClientIp = "192.168.1.202",
  [Parameter(Mandatory = $false)]
  [string]$TerminalHostName = "AMG-MANAGER3",
  [Parameter(Mandatory = $false)]
  [string]$TerminalIp = "192.168.1.82",
  [Parameter(Mandatory = $false)]
  [string]$TerminalReceiverLabel = "AMG-MANAGER3",
  [Parameter(Mandatory = $false)]
  [switch]$SkipInstall
)

$ErrorActionPreference = "Stop"

function Invoke-Main {
  $root = Resolve-Path (Join-Path $PSScriptRoot "..")
  Set-Location $root

  if (-not $SkipInstall.IsPresent) {
    Write-Host "[lan-bundles] installing workspace dependencies"
    corepack pnpm install
  }

  $envPath = if ([System.IO.Path]::IsPathRooted($EnvFile)) {
    $EnvFile
  } else {
    Join-Path $root $EnvFile
  }

  if (-not (Test-Path -LiteralPath $envPath)) {
    throw "Env file not found: $envPath"
  }

  $envMap = Read-EnvFile -Path $envPath
  $backend = (Get-EnvValue -EnvMap $envMap -Key "LOTTERY_STORAGE_BACKEND" -DefaultValue "in-memory").Trim().ToLowerInvariant()
  if ($backend -ne "postgres") {
    throw "LAN bundle requires LOTTERY_STORAGE_BACKEND=postgres in $envPath"
  }

  $sharedPostgresUrl = Resolve-PostgresUrl -EnvMap $envMap -ServerIp $ServerIp
  $resolvedServerPort = Resolve-ServerPort -EnvMap $envMap -FallbackPort $ServerPort
  $webBaseUrl = "http://$ServerIp`:$resolvedServerPort"
$clientUrl = "$webBaseUrl/lottery/bolshaya-8"
$terminalMonitorUrl = "$webBaseUrl/terminal/receiver"
$profileTag = (Get-Date -Format "yyyyMMdd-HHmmss")

  $nodeBinaryPath = Resolve-NodeBinaryPath
  $esbuildCliPath = Resolve-EsbuildCliPath -Root $root

  $outputRootPath = if ([System.IO.Path]::IsPathRooted($OutputRoot)) {
    $OutputRoot
  } else {
    Join-Path $root $OutputRoot
  }

  if (Test-Path -LiteralPath $outputRootPath) {
    Stop-BundleNodeProcesses -OutputRootPath $outputRootPath
    Remove-DirectoryWithRetry -Path $outputRootPath
  }

  $clientBundlePath = Join-Path $outputRootPath "client-workstation"
  $terminalBundlePath = Join-Path $outputRootPath "terminal-receiver"
  $terminalRuntimePath = Join-Path $terminalBundlePath "runtime"

  New-Item -ItemType Directory -Path $clientBundlePath -Force | Out-Null
  New-Item -ItemType Directory -Path $terminalBundlePath -Force | Out-Null
  New-Item -ItemType Directory -Path $terminalRuntimePath -Force | Out-Null

  Write-Host "[lan-bundles] building portable terminal runtime"
  Bundle-NodeScript -NodeBinaryPath $nodeBinaryPath -EsbuildCliPath $esbuildCliPath `
    -EntryPoint (Join-Path $root "apps/terminal-worker/src/main.ts") `
    -OutputFile (Join-Path $terminalRuntimePath "terminal-worker.cjs") `
    -TsconfigPath (Join-Path $root "tsconfig.base.json")
  Bundle-NodeScript -NodeBinaryPath $nodeBinaryPath -EsbuildCliPath $esbuildCliPath `
    -EntryPoint (Join-Path $root "scripts/runtime-preflight.ts") `
    -OutputFile (Join-Path $terminalRuntimePath "runtime-preflight.cjs") `
    -TsconfigPath (Join-Path $root "tsconfig.base.json")
  Copy-Item -LiteralPath $nodeBinaryPath -Destination (Join-Path $terminalRuntimePath "node.exe") -Force

  $terminalEnvLines = @(
    "# Generated by scripts/build-lan-bundles.ps1",
    "LOTTERY_STORAGE_BACKEND=postgres",
    "LOTTERY_POSTGRES_URL=$sharedPostgresUrl",
    "DATABASE_URL=$sharedPostgresUrl",
    "LOTTERY_TERMINAL_LOCK_TTL_SECONDS=30",
    "LOTTERY_TERMINAL_POLL_INTERVAL_MS=3000",
    "LOTTERY_BIG8_LIVE_DRAW_SYNC_ENABLED=true",
    "LOTTERY_BIG8_CART_AUTOMATION_ENABLED=true",
    "LOTTERY_BIG8_TERMINAL_MODE=mock",
    "LOTTERY_BIG8_MOCK_LATENCY_MS=250",
    "LOTTERY_TERMINAL_HANDLER_CODES=bolshaya-8",
    "LOTTERY_TERMINAL_RECEIVER_LABEL=$TerminalReceiverLabel"
  )
  Write-TextFile -Path (Join-Path $terminalBundlePath "terminal-receiver.env") -Value ($terminalEnvLines -join [Environment]::NewLine)

  $builtAt = (Get-Date).ToString("o")

  Write-JsonFile -Path (Join-Path $clientBundlePath "client-config.json") -Value @{
    builtAt = $builtAt
    webBaseUrl = $webBaseUrl
    clientUrl = $clientUrl
    serverIp = $ServerIp
    serverPort = $resolvedServerPort
  clientHostName = $ClientHostName
  clientIp = $ClientIp
  profileDirName = "chrome-profile-$profileTag"
}

  Write-JsonFile -Path (Join-Path $terminalBundlePath "terminal-config.json") -Value @{
    builtAt = $builtAt
    webBaseUrl = $webBaseUrl
    monitorUrl = $terminalMonitorUrl
    clientUrl = $clientUrl
    serverIp = $ServerIp
    serverPort = $resolvedServerPort
  terminalHostName = $TerminalHostName
  terminalIp = $TerminalIp
  receiverLabel = $TerminalReceiverLabel
  profileDirName = "chrome-profile-$profileTag"
}

  Write-ClientLaunchers -BundlePath $clientBundlePath
  Write-TerminalLaunchers -BundlePath $terminalBundlePath

  $clientReadme = @"
Copy this folder to client PC: $ClientHostName ($ClientIp)

Run:
- Start Client.cmd

What it does:
- opens Chrome/Edge in app mode
- targets $clientUrl
- keeps browser profile inside this folder

Central server requirements:
- web app must be running on $webBaseUrl
- client PC must see the server over LAN
"@
  Write-TextFile -Path (Join-Path $clientBundlePath "README.txt") -Value $clientReadme

  $terminalReadme = @"
Copy this folder to terminal PC: $TerminalHostName ($TerminalIp)

Run:
- Start Terminal Receiver.cmd

What it does:
- launches portable node runtime from this folder
- starts Big 8 mock terminal receiver against shared Postgres on $ServerIp
- opens receiver monitor at $terminalMonitorUrl
- writes logs to .\logs\

Central server requirements:
- web app must be running on $webBaseUrl
- PostgreSQL must accept LAN connections from terminal PC
"@
  Write-TextFile -Path (Join-Path $terminalBundlePath "README.txt") -Value $terminalReadme

  Write-JsonFile -Path (Join-Path $outputRootPath "bundle-manifest.json") -Value @{
    builtAt = $builtAt
    serverIp = $ServerIp
    serverPort = $resolvedServerPort
    webBaseUrl = $webBaseUrl
    clientBundle = @{
      path = $clientBundlePath
      hostName = $ClientHostName
      ip = $ClientIp
      launcher = "Start Client.cmd"
    }
    terminalBundle = @{
      path = $terminalBundlePath
      hostName = $TerminalHostName
      ip = $TerminalIp
      launcher = "Start Terminal Receiver.cmd"
      receiverLabel = $TerminalReceiverLabel
    }
  }

  Write-Host "[lan-bundles] ready"
  Write-Host "[lan-bundles] client bundle   -> $clientBundlePath"
  Write-Host "[lan-bundles] terminal bundle -> $terminalBundlePath"
}

function Read-EnvFile {
  param(
    [Parameter(Mandatory = $true)]
    [string]$Path
  )

  $result = @{}
  Get-Content -LiteralPath $Path | ForEach-Object {
    $line = $_.Trim()
    if ($line.Length -eq 0 -or $line.StartsWith("#")) {
      return
    }

    $parts = $line.Split("=", 2)
    if ($parts.Length -ne 2) {
      return
    }

    $key = $parts[0].Trim()
    if ($key.Length -eq 0) {
      return
    }

    $result[$key] = $parts[1]
  }

  return $result
}

function Get-EnvValue {
  param(
    [Parameter(Mandatory = $true)]
    [hashtable]$EnvMap,
    [Parameter(Mandatory = $true)]
    [string]$Key,
    [Parameter(Mandatory = $false)]
    [string]$DefaultValue = ""
  )

  if ($EnvMap.ContainsKey($Key) -and $null -ne $EnvMap[$Key]) {
    return [string]$EnvMap[$Key]
  }

  return $DefaultValue
}

function Resolve-PostgresUrl {
  param(
    [Parameter(Mandatory = $true)]
    [hashtable]$EnvMap,
    [Parameter(Mandatory = $true)]
    [string]$ServerIp
  )

  $rawValue = (Get-EnvValue -EnvMap $EnvMap -Key "LOTTERY_POSTGRES_URL" -DefaultValue "")
  if ($rawValue.Trim().Length -eq 0) {
    $rawValue = Get-EnvValue -EnvMap $EnvMap -Key "DATABASE_URL" -DefaultValue ""
  }
  if ($rawValue.Trim().Length -eq 0) {
    throw "LOTTERY_POSTGRES_URL (or DATABASE_URL) is required to build LAN bundles"
  }

  $uriBuilder = [System.UriBuilder]::new($rawValue)
  $uriBuilder.Host = $ServerIp
  return $uriBuilder.Uri.AbsoluteUri
}

function Resolve-ServerPort {
  param(
    [Parameter(Mandatory = $true)]
    [hashtable]$EnvMap,
    [Parameter(Mandatory = $true)]
    [int]$FallbackPort
  )

  $rawPort = (Get-EnvValue -EnvMap $EnvMap -Key "PORT" -DefaultValue "").Trim()
  if ($rawPort.Length -eq 0) {
    return $FallbackPort
  }

  $parsedPort = 0
  if ([int]::TryParse($rawPort, [ref]$parsedPort) -and $parsedPort -ge 1 -and $parsedPort -le 65535) {
    return $parsedPort
  }

  return $FallbackPort
}

function Resolve-NodeBinaryPath {
  $command = Get-Command node -ErrorAction SilentlyContinue
  if ($command -and (Test-Path -LiteralPath $command.Source)) {
    return $command.Source
  }

  $fallbackPath = "C:\Program Files\nodejs\node.exe"
  if (Test-Path -LiteralPath $fallbackPath) {
    return $fallbackPath
  }

  throw "Node.js binary not found. Install Node.js 20+ before building bundles."
}

function Resolve-EsbuildCliPath {
  param(
    [Parameter(Mandatory = $true)]
    [string]$Root
  )

  $candidate = Get-ChildItem -Path (Join-Path $Root "node_modules/.pnpm") -Directory -ErrorAction SilentlyContinue |
    Where-Object { $_.Name -like "esbuild@*" } |
    Sort-Object Name -Descending |
    Select-Object -First 1

  if (-not $candidate) {
    throw "esbuild package not found under node_modules/.pnpm. Run corepack pnpm install first."
  }

  $cliPath = Join-Path $candidate.FullName "node_modules/esbuild/bin/esbuild"
  if (-not (Test-Path -LiteralPath $cliPath)) {
    throw "esbuild CLI not found at $cliPath"
  }

  return $cliPath
}

function Stop-BundleNodeProcesses {
  param(
    [Parameter(Mandatory = $true)]
    [string]$OutputRootPath
  )

  $normalizedRoot = [System.IO.Path]::GetFullPath($OutputRootPath)
  $runningNodes = Get-Process node -ErrorAction SilentlyContinue | Where-Object {
    $_.Path -and [System.IO.Path]::GetFullPath($_.Path).StartsWith($normalizedRoot, [System.StringComparison]::OrdinalIgnoreCase)
  }

  foreach ($process in $runningNodes) {
    Stop-Process -Id $process.Id -Force
    Wait-Process -Id $process.Id -Timeout 10 -ErrorAction SilentlyContinue
  }
}

function Remove-DirectoryWithRetry {
  param(
    [Parameter(Mandatory = $true)]
    [string]$Path
  )

  for ($attempt = 1; $attempt -le 10; $attempt++) {
    try {
      Remove-Item -LiteralPath $Path -Recurse -Force
      return
    } catch {
      if ($attempt -eq 10) {
        throw
      }
      Start-Sleep -Milliseconds 400
    }
  }
}

function Bundle-NodeScript {
  param(
    [Parameter(Mandatory = $true)]
    [string]$NodeBinaryPath,
    [Parameter(Mandatory = $true)]
    [string]$EsbuildCliPath,
    [Parameter(Mandatory = $true)]
    [string]$EntryPoint,
    [Parameter(Mandatory = $true)]
    [string]$OutputFile,
    [Parameter(Mandatory = $true)]
    [string]$TsconfigPath
  )

  & $NodeBinaryPath $EsbuildCliPath $EntryPoint `
    "--bundle" `
    "--platform=node" `
    "--format=cjs" `
    "--outfile=$OutputFile" `
    "--tsconfig=$TsconfigPath"

  if ($LASTEXITCODE -ne 0) {
    throw "esbuild failed for $EntryPoint"
  }
}

function Write-JsonFile {
  param(
    [Parameter(Mandatory = $true)]
    [string]$Path,
    [Parameter(Mandatory = $true)]
    [object]$Value
  )

  $json = $Value | ConvertTo-Json -Depth 8
  Write-TextFile -Path $Path -Value $json
}

function Write-TextFile {
  param(
    [Parameter(Mandatory = $true)]
    [string]$Path,
    [Parameter(Mandatory = $true)]
    [string]$Value
  )

  Set-Content -LiteralPath $Path -Value $Value -Encoding ascii
}

function Write-ClientLaunchers {
  param(
    [Parameter(Mandatory = $true)]
    [string]$BundlePath
  )

  $clientScript = @'
param(
  [switch]$NoBrowser
)

$ErrorActionPreference = "Stop"

function Resolve-BrowserPath {
  $candidates = @(
    "C:\Program Files\Google\Chrome\Application\chrome.exe",
    "C:\Program Files (x86)\Google\Chrome\Application\chrome.exe",
    "C:\Program Files\Microsoft\Edge\Application\msedge.exe",
    "C:\Program Files (x86)\Microsoft\Edge\Application\msedge.exe"
  )

  foreach ($candidate in $candidates) {
    if (Test-Path -LiteralPath $candidate) {
      return $candidate
    }
  }

  return $null
}

function Resolve-ProfileDir {
  param(
    [Parameter(Mandatory = $true)]
    [string]$BundleRoot
  )

  $profilesRoot = Join-Path $BundleRoot "profiles"
  New-Item -ItemType Directory -Path $profilesRoot -Force | Out-Null

  $profileDir = Join-Path $profilesRoot ("chrome-profile-" + (Get-Date -Format "yyyyMMdd-HHmmss"))
  New-Item -ItemType Directory -Path $profileDir -Force | Out-Null
  return $profileDir
}

$bundleRoot = Split-Path -Parent $MyInvocation.MyCommand.Path
$configPath = Join-Path $bundleRoot "client-config.json"
$config = Get-Content -LiteralPath $configPath -Raw | ConvertFrom-Json
$profileDir = Resolve-ProfileDir -BundleRoot $bundleRoot

if ($NoBrowser.IsPresent) {
  return
}

$browserPath = Resolve-BrowserPath
if ($browserPath) {
  Start-Process -FilePath $browserPath -ArgumentList @(
    "--app=$($config.clientUrl)",
    "--user-data-dir=$profileDir",
    "--disable-extensions",
    "--disable-sync",
    "--no-first-run",
    "--no-default-browser-check",
    "--start-maximized"
  ) | Out-Null
  return
}

Start-Process -FilePath $config.clientUrl | Out-Null
'@

  $clientCmd = @'
@echo off
setlocal
powershell -ExecutionPolicy Bypass -File "%~dp0Start Client.ps1"
'@

  Write-TextFile -Path (Join-Path $BundlePath "Start Client.ps1") -Value $clientScript
  Write-TextFile -Path (Join-Path $BundlePath "Start Client.cmd") -Value $clientCmd
}

function Write-TerminalLaunchers {
  param(
    [Parameter(Mandatory = $true)]
    [string]$BundlePath
  )

  $terminalScript = @'
param(
  [switch]$NoBrowser
)

$ErrorActionPreference = "Stop"

function Import-DotEnvFile {
  param(
    [Parameter(Mandatory = $true)]
    [string]$Path
  )

  Get-Content -LiteralPath $Path | ForEach-Object {
    $line = $_.Trim()
    if ($line.Length -eq 0 -or $line.StartsWith("#")) {
      return
    }

    $parts = $line.Split("=", 2)
    if ($parts.Length -ne 2) {
      return
    }

    [Environment]::SetEnvironmentVariable($parts[0].Trim(), $parts[1], "Process")
  }
}

function Resolve-BrowserPath {
  $candidates = @(
    "C:\Program Files\Google\Chrome\Application\chrome.exe",
    "C:\Program Files (x86)\Google\Chrome\Application\chrome.exe",
    "C:\Program Files\Microsoft\Edge\Application\msedge.exe",
    "C:\Program Files (x86)\Microsoft\Edge\Application\msedge.exe"
  )

  foreach ($candidate in $candidates) {
    if (Test-Path -LiteralPath $candidate) {
      return $candidate
    }
  }

  return $null
}

function Resolve-ProfileDir {
  param(
    [Parameter(Mandatory = $true)]
    [string]$BundleRoot
  )

  $profilesRoot = Join-Path $BundleRoot "profiles"
  New-Item -ItemType Directory -Path $profilesRoot -Force | Out-Null

  $profileDir = Join-Path $profilesRoot ("chrome-profile-" + (Get-Date -Format "yyyyMMdd-HHmmss"))
  New-Item -ItemType Directory -Path $profileDir -Force | Out-Null
  return $profileDir
}

function Get-ExistingWorkerProcess {
  param(
    [Parameter(Mandatory = $true)]
    [string]$PidFile
  )

  if (-not (Test-Path -LiteralPath $PidFile)) {
    return $null
  }

  $rawPid = (Get-Content -LiteralPath $PidFile -Raw).Trim()
  if ($rawPid.Length -eq 0) {
    Remove-Item -LiteralPath $PidFile -Force -ErrorAction SilentlyContinue
    return $null
  }

  try {
    $process = Get-Process -Id $rawPid -ErrorAction Stop
    return $process
  } catch {
    Remove-Item -LiteralPath $PidFile -Force -ErrorAction SilentlyContinue
    return $null
  }
}

$bundleRoot = Split-Path -Parent $MyInvocation.MyCommand.Path
$runtimeRoot = Join-Path $bundleRoot "runtime"
$configPath = Join-Path $bundleRoot "terminal-config.json"
$envPath = Join-Path $bundleRoot "terminal-receiver.env"
$logsDir = Join-Path $bundleRoot "logs"
$runDir = Join-Path $bundleRoot "run"
$pidFile = Join-Path $runDir "terminal-worker.pid"
$stdoutPath = Join-Path $logsDir "terminal-worker.stdout.log"
$stderrPath = Join-Path $logsDir "terminal-worker.stderr.log"

Import-DotEnvFile -Path $envPath
$config = Get-Content -LiteralPath $configPath -Raw | ConvertFrom-Json
$profileDir = Resolve-ProfileDir -BundleRoot $bundleRoot

foreach ($path in @($logsDir, $runDir, $profileDir)) {
  New-Item -ItemType Directory -Path $path -Force | Out-Null
}

$preflightScript = Join-Path $runtimeRoot "runtime-preflight.cjs"
$workerScript = Join-Path $runtimeRoot "terminal-worker.cjs"
$nodeBinary = Join-Path $runtimeRoot "node.exe"

& $nodeBinary $preflightScript "--role=worker" "--env=$envPath"
if ($LASTEXITCODE -ne 0) {
  throw "terminal receiver preflight failed"
}

$existingWorker = Get-ExistingWorkerProcess -PidFile $pidFile
$workerProcess = $existingWorker
if (-not $existingWorker) {
  $workerProcess = Start-Process -FilePath $nodeBinary `
    -ArgumentList @($workerScript) `
    -WorkingDirectory $runtimeRoot `
    -WindowStyle Hidden `
    -RedirectStandardOutput $stdoutPath `
    -RedirectStandardError $stderrPath `
    -PassThru

  Set-Content -LiteralPath $pidFile -Value $workerProcess.Id
}

if ($NoBrowser.IsPresent) {
  if ($workerProcess) {
    Write-Host "[receiver] worker pid=$($workerProcess.Id)"
  }
  return
}

$browserPath = Resolve-BrowserPath
if ($browserPath) {
  Start-Process -FilePath $browserPath -ArgumentList @(
    "--app=$($config.monitorUrl)",
    "--user-data-dir=$profileDir",
    "--disable-extensions",
    "--disable-sync",
    "--no-first-run",
    "--no-default-browser-check",
    "--start-maximized"
  ) | Out-Null
} else {
  Start-Process -FilePath $config.monitorUrl | Out-Null
}

if ($workerProcess) {
  Write-Host "[receiver] worker pid=$($workerProcess.Id)"
}
Write-Host "[receiver] monitor url: $($config.monitorUrl)"
Write-Host "[receiver] stdout log: $stdoutPath"
Write-Host "[receiver] stderr log: $stderrPath"
Write-Host "[receiver] close this window to stop log view only; worker keeps running"
Get-Content -LiteralPath @($stdoutPath, $stderrPath) -Tail 20 -Wait
'@

  $terminalCmd = @'
@echo off
setlocal
powershell -ExecutionPolicy Bypass -File "%~dp0Start Terminal Receiver.ps1"
'@

  Write-TextFile -Path (Join-Path $BundlePath "Start Terminal Receiver.ps1") -Value $terminalScript
  Write-TextFile -Path (Join-Path $BundlePath "Start Terminal Receiver.cmd") -Value $terminalCmd
}

Invoke-Main
